FROM docker-registry.cfdata.org/stash/cf/debian-images/bookworm/main:2023.10.1

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        bash \
        iputils-ping \
        curl \
        dnsutils && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]
