apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etl-data-pvc
  namespace: di-kubernets-staging
spec:
  accessModes:
    - ReadWriteMany  # Allows multiple pods to read/write simultaneously
  resources:
    requests:
      storage: 6Ti  # Increased to handle 4TB plus processing overhead
  storageClassName: your-storage-class  # CHANGE THIS to your on-prem storage class
