apiVersion: batch/v1
kind: Job
metadata:
  name: etl-controller-job
  namespace: di-kubernets-staging
  labels:
    app: etl-controller
spec:
  template:
    metadata:
      labels:
        app: etl-controller  # ✅ Needed for NetworkPolicy matching
    spec:
      serviceAccountName: etl-controller-sa
      automountServiceAccountToken: true
      containers:
      - name: controller
        image: docker-registry.cfdata.org/u/santhoshi/pg_stripe/58/etl-controller:latest@sha256:1168d410d155a37abcb3b6a0d44937c92f51cf0158a8759bc1489cfd9e256cfe
        imagePullPolicy: Always
        resources:
          requests:
            memory: "3Gi"
            cpu: "2000m"
          limits:
            memory: "4Gi"
            cpu: "3"
        env:
        - name: DB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: connection-string
        - name: BIGQUERY_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: gcp-credentials-base64
              key: credentials
        - name: MAX_CONCURRENT_EXTRACTIONS
          value: "10"
        - name: MAX_CONCURRENT_LOADS
          value: "5"
        - name: CHUNK_SIZE_MB
          value: "500"
        - name: BIGQUERY_PROJECT
          value: "cloudflare-datainsights"
        - name: BIGQUERY_DATASET
          value: "prod_entitlements_stage"
        volumeMounts:
        - name: job-templates
          mountPath: /app/templates
      volumes:
      - name: job-templates
        configMap:
          name: etl-job-templates
      restartPolicy: OnFailure
