apiVersion: v1
kind: ServiceAccount
metadata:
  name: etl-controller
  namespace: di-kubernets-staging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: etl-controller
  namespace: di-kubernets-staging
rules:
  - apiGroups: [""]
    resources: ["pods", "secrets", "services", "configmaps"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["cosmas.k8s.cloudflare.com"]
    resources: ["resourceallocations"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: etl-controller
  namespace: di-kubernets-staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: etl-controller
subjects:
  - kind: ServiceAccount
    name: etl-controller
    namespace: di-kubernets-staging
